var proper = require("properties-parser");
var colors = require('colors');

var PORT_WEB = "port_web";
var MONGODB_PORT = "mongodb_port";
var MONGODB_IP = "mongodb_ip";
var USERNAME = "username";
var PASSWORD = "password";
var NAME_DATABASE = "name_database";
var KEY = "key";
var SECRET = "secret";
var SEND_MAIL = "send_mail";
var USER_MAIL = "user_mail";
var PASSWORD_MAIL = "password_mail";
var HOST = "host";
var SSL = "ssl";
var SUBJECT = "subject";
var FROM = "from";
var TO = "to";
var DATE_FORMAT = "date_format";

var p = {};

p.loadProperties = function(next) {
  proper.read('./acra_server.properties', function(err, data) {
    console.log("------------------------".red);
    console.log("ACRA SERVER LOG 0.0.4".bold.red);
    console.log("------------------------".red);
    console.log("Loading properties sync before start server...".red);
    console.log("------------------------".red);
    p.portWeb = portWeb = data[PORT_WEB];
    console.log("port_web:"+p.portWeb.red);
    p.mongodbPort = mongodbPort = data[MONGODB_PORT];
    console.log("mongodbPort:"+p.mongodbPort.red);
    p.mongodbIp = mongodbIp = data[MONGODB_IP];
    console.log("mongodbIp:"+p.mongodbIp.red);
    p.username = username = data[USERNAME];
    console.log("username:"+p.username.red);
    p.password = password = data[PASSWORD];
    console.log("password:"+p.password.red);
    p.name_database = name_database = data[NAME_DATABASE];
    console.log("name_database:"+p.name_database.red);
    p.secret = secret = data[SECRET];
    console.log("secret:"+p.secret.red);
    p.key = key = data[KEY];
    console.log("key:"+p.key.red);
    p.send_mail = send_mail = data[SEND_MAIL];
    console.log("send_mail:"+p.send_mail.red);
    p.user_mail = user_mail = data[USER_MAIL];
    console.log("user_mail:"+p.user_mail.red);
    p.password_mail = password_mail = data[PASSWORD_MAIL];
    console.log("password_mail:"+p.password_mail.red);
    p.host = host = data[HOST];
    console.log("host:"+p.host.red);
    p.ssl = ssl = data[SSL];
    console.log("ssl:"+p.ssl.red);
    p.subject = subject = data[SUBJECT];
    console.log("subject:"+p.subject.red);
    p.from = from = data[FROM];
    console.log("from:"+from.red);
    p.to = to = data[TO];
    console.log("to:"+p.to.red);
    p.date_format = date_format = data[DATE_FORMAT];
    console.log("date_format:"+p.date_format.red);
    console.log("------------------------".red);
    next();
  });
};

module.exports = p;
